// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGs_ChlB3NRWr4FoSwpoGszce6-x8j4ck',
    appId: '1:187309354275:web:2bcf00df7c9915c21d3096',
    messagingSenderId: '187309354275',
    projectId: 'fir-app-6cc48',
    authDomain: 'fir-app-6cc48.firebaseapp.com',
    storageBucket: 'fir-app-6cc48.appspot.com',
    measurementId: 'G-FZ58EN4QTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8q35ZKWs0CnnD6MoGqmhHAbaVlHW4ic',
    appId: '1:187309354275:android:4d64c69a4d195c361d3096',
    messagingSenderId: '187309354275',
    projectId: 'fir-app-6cc48',
    storageBucket: 'fir-app-6cc48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1vdn_OQFRFtMCEXwb9RgKPin5M60SaM',
    appId: '1:187309354275:ios:2681d9c10236d67e1d3096',
    messagingSenderId: '187309354275',
    projectId: 'fir-app-6cc48',
    storageBucket: 'fir-app-6cc48.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1vdn_OQFRFtMCEXwb9RgKPin5M60SaM',
    appId: '1:187309354275:ios:28c34b88d5b7cb3d1d3096',
    messagingSenderId: '187309354275',
    projectId: 'fir-app-6cc48',
    storageBucket: 'fir-app-6cc48.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
